# Generated by Django 4.0.5 on 2022-07-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CafeOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(default="", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("slug", models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeShopAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(default="", max_length=40)),
                ("line2", models.CharField(default="", max_length=40)),
                ("city", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("price", models.DecimalField(decimal_places=3, max_digits=7)),
                ("stock_count", models.PositiveIntegerField()),
                ("is_out_of_stock", models.BooleanField(editable=False)),
                (
                    "coffee_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drinks",
                        to="coffeeshops.coffeeshop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coffee_shop",
                to="coffeeshops.coffeeshopaddress",
            ),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coffee_shops",
                to="coffeeshops.cafeowner",
            ),
        ),
    ]
